import{describe,it,expect}from'vitest';import{mkdtemp,writeFile,readFile,lstat,symlink,chmod,realpath}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{Client}from'@modelcontextprotocol/sdk/client/index.js';import{InMemoryTransport}from'@modelcontextprotocol/sdk/inMemory.js';import{loadConfig}from'../src/config.js';import{BannerbearClient}from'../src/api/client.js';import{ALL_TOOLS,validateArguments}from'../src/tools/index.js';import{buildServer}from'../src/server.js';
const fakeKey='fixture_key_not_a_real_secret';const cfg=(extra:Record<string,string>={})=>loadConfig({BANNERBEAR_API_KEY:fakeKey,BANNERBEAR_MIN_REQUEST_INTERVAL_MS:'0',...extra});
const response=(x:unknown,status=200)=>new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json'}});
async function session(fetcher:typeof fetch,extra:Record<string,string>={}){const c=cfg(extra);const s=buildServer(c,new BannerbearClient(c,fetcher));const a=new Client({name:'fixture-test',version:'1'}),[clientT,serverT]=InMemoryTransport.createLinkedPair();await s.connect(serverT);await a.connect(clientT);return{call:async(name:string,args:Record<string,unknown>)=>a.callTool({name,arguments:args}),close:async()=>{await a.close();await s.close();}};}
function parse(r:any){return JSON.parse(r.content[0].text);}
const image={template:'fixture_template',modifications:{objects:[{name:'title',text:'Hello'}]}};
const batch={type:'images',items:[image]};
const never=(async()=>{throw Error('Unexpected request');})as typeof fetch;
describe('current V5 payloads and shared safeguards',()=>{
 it('refuses image generation and deletion before fetch without confirmation',async()=>{let calls=0;const s=await session((async()=>{calls++;return response({});})as typeof fetch);try{for(const[name,args]of[['create_image',{payload:image}],['delete_image_template',{uid:'fixture_template'}]]as const){const r=await s.call(name,args);expect(r.isError).toBe(true);expect(JSON.stringify(r)).toContain('confirm: true');}expect(calls).toBe(0);}finally{await s.close();}});
 it('submits exactly one async V5 render with the exact body',async()=>{let calls=0;const s=await session((async(u,init)=>{calls++;expect(String(u)).toBe('https://api.bannerbear.com/v5/images');expect(init?.method).toBe('POST');expect(init?.redirect).toBe('error');expect(JSON.parse(init?.body as string)).toEqual(image);return response({uid:'fixture_render',status:'pending'},202);})as typeof fetch);try{const r=await s.call('create_image',{payload:image,confirm:true});expect(r.isError).not.toBe(true);expect(parse(r).status).toBe('pending');expect(calls).toBe(1);}finally{await s.close();}});
 it('hides all mutations and refuses confirmed direct calls',async()=>{const s=await session(never,{BANNERBEAR_READ_ONLY:'true'});try{const r=await s.call('delete_image_template',{uid:'fixture',confirm:true});expect(r.isError).toBe(true);expect(JSON.stringify(r)).toContain('READ_ONLY');}finally{await s.close();}});
 it('does not let agent yes change the shared mandatory policy',async()=>{const s=await session(never,{BANNERBEAR_ALLOW_DESTRUCTIVE:'0'});try{expect((await s.call('create_image',{payload:image,confirm:true})).isError).toBe(true);}finally{await s.close();}});
 it('refuses a V2 modifications array and unknown native fields locally',()=>{const t=ALL_TOOLS.find(x=>x.name==='create_image')!;expect(()=>validateArguments(t,{payload:{template:'fixture',modifications:[]}})).toThrow();expect(()=>validateArguments(t,{payload:{...image,webhook_url:'https://example.com'}})).toThrow();});
 it('accepts V5 formats, nullable native fields and layer schemas',()=>{validateArguments(ALL_TOOLS.find(x=>x.name==='create_image')!,{payload:{...image,formats:['avif','pdf'],scale:2,quality:90}});validateArguments(ALL_TOOLS.find(x=>x.name==='create_image_template')!,{payload:{name:'Test',description:null,config:{objects:[{id:'title',type:'text',text:'Hello'}]}}});});
 it('enforces native batch maximum 100 before any submission',async()=>{const s=await session(never);try{expect((await s.call('create_batch',{payload:{type:'images',items:Array(101).fill(image)},confirm:true})).isError).toBe(true);}finally{await s.close();}});
 it('refuses empty native batches',()=>expect(()=>validateArguments(ALL_TOOLS.find(x=>x.name==='create_batch')!,{payload:{type:'images',items:[]}})).toThrow());
 it('refuses unsafe UID traversal and undeclared hosts',async()=>{const s=await session(never);try{expect((await s.call('get_image',{uid:'../account'})).isError).toBe(true);expect((await s.call('get_image',{uid:'fixture',host:'https://example.com'})).isError).toBe(true);}finally{await s.close();}});
 it('previews without configured keys and makes no request',async()=>{const s=await session(never,{BANNERBEAR_API_KEY:''});try{const r=await s.call('preview_operation',{operation:'create_image',arguments:{payload:image}});expect(r.isError).not.toBe(true);expect(parse(r)).toMatchObject({method:'POST',path:'/images',localOnly:true,providerValidated:false});}finally{await s.close();}});
 it('requires payload and payload_file to be exclusive',async()=>{const s=await session(never);try{expect((await s.call('create_image',{payload:image,payload_file:'/nonexistent',confirm:true})).isError).toBe(true);}finally{await s.close();}});
 it('requires an actual native body even though discovery stays credential-free',async()=>{const s=await session(never);try{expect((await s.call('create_image',{confirm:true})).isError).toBe(true);}finally{await s.close();}});
});
describe('profiles and private files',()=>{
 it('isolates explicit profiles from the global credential',()=>{const c=cfg({BANNERBEAR_ACCOUNTS:JSON.stringify([{name:'separate'}])});expect(c.accounts[0]?.apiToken).toBe('');});
 it('refuses duplicate or unknown default labels',()=>{expect(()=>cfg({BANNERBEAR_ACCOUNTS:'[{"name":"a"},{"name":"a"}]'})).toThrow();expect(()=>cfg({BANNERBEAR_DEFAULT_ACCOUNT:'absent'})).toThrow();});
 it('routes the exact named private profile key',async()=>{const c=cfg({BANNERBEAR_ACCOUNTS:'[{"name":"a","api_key":"fixture_a"},{"name":"b","api_key":"fixture_b"}]'});let header='';await new BannerbearClient(c,(async(_u,i)=>{header=(i?.headers as Record<string,string>).Authorization;return response({uid:'fixture'});})as typeof fetch).request('GET','/images/fixture',[],undefined,'b');expect(header).toBe('Bearer fixture_b');});
 it('lists labels only, without tokens, paths or identity',async()=>{const s=await session(never);try{const r=parse(await s.call('list_accounts',{}));expect(JSON.stringify(r)).not.toContain(fakeKey);expect(r.accounts).toEqual([{name:'default',default:true,auth:'api_key'}]);}finally{await s.close();}});
 it('reads a private token file without echoing it',async()=>{const d=await mkdtemp(join(tmpdir(),'bb-private-'));const file=join(d,'token');await writeFile(file,fakeKey,{mode:0o600});const c=cfg({BANNERBEAR_API_KEY:'',BANNERBEAR_TOKEN_FILE:file});const client=new BannerbearClient(c,(async()=>response({echo:fakeKey}))as typeof fetch);expect(await client.request('GET','/account')).toEqual({echo:'[redacted]'});});
 it.skipIf(process.platform==='win32')('refuses readable-by-others token files',async()=>{const d=await mkdtemp(join(tmpdir(),'bb-token-permissions-'));const file=join(d,'token');await writeFile(file,fakeKey,{mode:0o644});await expect(new BannerbearClient(cfg({BANNERBEAR_TOKEN_FILE:file}),never).request('GET','/account')).rejects.toThrow(/private Bannerbear token file/);});
 it.skipIf(process.platform==='win32')('refuses token-file symlinks',async()=>{const d=await mkdtemp(join(tmpdir(),'bb-symlink-'));const file=join(d,'token');await writeFile(file,fakeKey,{mode:0o600});await symlink(file,join(d,'link'));await expect(new BannerbearClient(cfg({BANNERBEAR_TOKEN_FILE:join(d,'link')}),never).request('GET','/account')).rejects.toThrow();});
 it('requires a private result file before creating a webhook',async()=>{const s=await session(never);try{expect((await s.call('create_webhook',{payload:{name:'Test',url:'https://example.com/hook'},confirm:true})).isError).toBe(true);}finally{await s.close();}});
 it('writes the creation signing key exclusively and redacts model output',async()=>{const d=await mkdtemp(join(tmpdir(),'bb-signing-key-'));await chmod(d,0o700);const file=join(await realpath(d),'result.json');const s=await session((async()=>response({uid:'fixture_webhook',signing_key:'fixture_signing_key'},201))as typeof fetch);try{const r=await s.call('create_webhook',{payload:{name:'Test',url:'https://example.com/hook'},secret_result_file:file,confirm:true});expect(r.isError).not.toBe(true);expect(JSON.stringify(r)).not.toContain('fixture_signing_key');expect(JSON.parse(await readFile(file,'utf8')).result.signing_key).toBe('fixture_signing_key');if(process.platform!=='win32')expect((await lstat(file)).mode&0o777).toBe(0o600);}finally{await s.close();}});
 it('refuses to overwrite an existing secret result before fetch',async()=>{const d=await mkdtemp(join(tmpdir(),'bb-existing-'));await chmod(d,0o700);const file=join(d,'result');await writeFile(file,'keep');const s=await session(never);try{expect((await s.call('create_instant_url',{payload:{name:'Test',template:'fixture'},secret_result_file:file,confirm:true})).isError).toBe(true);expect(await readFile(file,'utf8')).toBe('keep');}finally{await s.close();}});
 it('uploads confirmed bounded raw bytes with the declared MIME type',async()=>{const d=await mkdtemp(join(tmpdir(),'bb-asset-'));const file=join(d,'image');await writeFile(file,Buffer.from([1,2,3]));const s=await session((async(_u,i)=>{expect(Buffer.isBuffer(i?.body)).toBe(true);expect((i?.headers as Record<string,string>)['Content-Type']).toBe('image/png');return response({uid:'fixture_asset'},201);})as typeof fetch);try{expect((await s.call('upload_asset',{asset_file:file,content_type:'image/png',confirm:true})).isError).not.toBe(true);}finally{await s.close();}});
 it('refuses oversized assets before fetch',async()=>{const d=await mkdtemp(join(tmpdir(),'bb-large-'));const file=join(d,'asset');await writeFile(file,Buffer.alloc(5000001));const s=await session(never);try{expect((await s.call('upload_asset',{asset_file:file,content_type:'image/png',confirm:true})).isError).toBe(true);}finally{await s.close();}});
});
describe('no replay, bounded retrieval and exact review',()=>{
 for(const status of[429,500,408])it('does not replay HTTP '+status,async()=>{let calls=0;const c=new BannerbearClient(cfg(),(async()=>{calls++;return response({message:'fixture failure'},status);})as typeof fetch);await expect(c.request('POST','/images',[],image)).rejects.toThrow();expect(calls).toBe(1);});
 it('does not replay uncertain network outcomes',async()=>{let calls=0;const c=new BannerbearClient(cfg(),(async()=>{calls++;throw Error();})as typeof fetch);await expect(c.request('POST','/images',[],image)).rejects.toThrow(/unknown/);expect(calls).toBe(1);});
 it('maps exhausted credit responses distinctly',async()=>{await expect(new BannerbearClient(cfg(),(async()=>response({message:'credits exhausted'},402))as typeof fetch).request('POST','/images',[],image)).rejects.toMatchObject({status:402,code:'RATE_LIMIT'});});
 it('preserves account scope metadata while removing actual keys and signed URLs',()=>{const c=new BannerbearClient(cfg(),never);expect(c.sanitize({api_key:{name:'Test',scopes:['images:read']},signing_key:'fixture_secret',url:'https://example.com/?signature=fixture_secret',text:fakeKey})).toEqual({api_key:{name:'Test',scopes:['images:read']},signing_key:'[redacted]',url:'[private credential URL]',text:'[redacted]'});});
 it('reads at most the requested pages and returns an exact continuation',async()=>{let calls=0;const s=await session((async(u)=>{calls++;expect(new URL(String(u)).searchParams.get('page')).toBe(String(calls));return response([{uid:'fixture_'+calls}]);})as typeof fetch);try{const r=parse(await s.call('query_pages',{operation:'list_images',arguments:{},max_pages:2}));expect(r.pagesRead).toBe(2);expect(r.resumePage).toBe(3);expect(r.continuationUnknown).toBe(true);expect(calls).toBe(2);}finally{await s.close();}});
 it('stops pagination on an empty page',async()=>{let calls=0;const s=await session((async()=>{calls++;return response([]);})as typeof fetch);try{expect(parse(await s.call('query_pages',{operation:'list_images',arguments:{},max_pages:5})).emptyPageReached).toBe(true);expect(calls).toBe(1);}finally{await s.close();}});
 it('polls only existing UID and stops on completion',async()=>{let calls=0;const s=await session((async(u,i)=>{expect(i?.method).toBe('GET');expect(String(u)).toContain('/workflow_runs/fixture');calls++;return response({uid:'fixture',status:calls===1?'queued':'completed'});})as typeof fetch);try{const r=parse(await s.call('poll_job',{resource:'workflow_runs',uid:'fixture',max_polls:3,interval_ms:100}));expect(r.terminal).toBe(true);expect(r.reads).toBe(2);}finally{await s.close();}});
 it('does not mislabel an unknown job state as success',async()=>{const s=await session((async()=>response({status:'unexpected'}))as typeof fetch);try{expect(parse(await s.call('poll_job',{resource:'images',uid:'fixture'}))).toMatchObject({terminal:false,continuationUnknown:true,reads:1});}finally{await s.close();}});
 it('stops polling at the explicit maximum without resubmission',async()=>{let calls=0;const s=await session((async()=>{calls++;return response({status:'pending'});})as typeof fetch);try{expect(parse(await s.call('poll_job',{resource:'images',uid:'fixture',max_polls:1})).limitReached).toBe(true);expect(calls).toBe(1);}finally{await s.close();}});
 it('binds review to exact body, item order and profile before one submission',async()=>{let calls=0;const s=await session((async()=>{calls++;return response({uid:'fixture_batch',status:'pending'},202);})as typeof fetch);try{const p=parse(await s.call('preview_render_batch',{payload:batch}));expect(calls).toBe(0);expect((await s.call('apply_render_batch',{payload:{...batch,items:[{...image,metadata:'changed'}]},preview_sha256:p.preview_sha256,confirm:true})).isError).toBe(true);expect(calls).toBe(0);expect((await s.call('apply_render_batch',{payload:batch,preview_sha256:p.preview_sha256,confirm:true})).isError).not.toBe(true);expect(calls).toBe(1);}finally{await s.close();}});
 it('a review digest does not grant confirmation',async()=>{const s=await session(never);try{const p=parse(await s.call('preview_render_batch',{payload:batch}));expect((await s.call('apply_render_batch',{payload:batch,preview_sha256:p.preview_sha256})).isError).toBe(true);}finally{await s.close();}});
 it('reads native existence POSTs without treating them as writes',async()=>{const s=await session((async(_u,i)=>{expect(i?.method).toBe('POST');return response({exists:[]});})as typeof fetch,{BANNERBEAR_READ_ONLY:'1'});try{expect((await s.call('check_assets',{payload:{content_hashes:['a'.repeat(64)]}})).isError).not.toBe(true);}finally{await s.close();}});
});
