import{open,lstat}from'node:fs/promises';import{constants}from'node:fs';import{isAbsolute}from'node:path';
import{selectAccount,type Account,type Config}from'../config.js';import{BannerbearError,UsageError}from'./errors.js';
export type Json=Record<string,any>;export type QueryParam={name:string;value:unknown};
export class BannerbearClient{
 private tokens=new Map<string,string>();private schedules=new Map<string,Promise<void>>();private nextAt=new Map<string,number>();
 constructor(readonly config:Config,private readonly fetcher:typeof fetch=fetch,private readonly sleep:(ms:number)=>Promise<void>=(ms)=>new Promise(r=>setTimeout(r,ms))){}
 redactText(text:string){for(const secret of [...this.config.accounts.map(a=>a.apiToken),...this.tokens.values()].filter(Boolean).sort((a,b)=>b.length-a.length))text=text.split(secret).join('[redacted]');return text.replace(/https?:\/\/[^\s"<>]*(?:X-Amz-Signature|[?&](?:token|signature|sig|key|access_token)=)[^\s"<>]*/gi,'[private credential URL]');}
 sanitize(v:unknown):unknown{if(typeof v==='string')return this.redactText(v);if(Array.isArray(v))return v.map(x=>this.sanitize(x));if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,/^(password|secret|signing_key|signing_secret|api_token|token|access_token|refresh_token|authorization|client_secret)$/i.test(k)||(/^api_key$/i.test(k)&&typeof x==='string')?'[redacted]':this.sanitize(x)]));return v;}
 private async token(a:Account){if(this.tokens.has(a.name))return this.tokens.get(a.name)!;let token=a.apiToken;if(a.tokenFile){let file;try{if(!isAbsolute(a.tokenFile))throw Error();const before=await lstat(a.tokenFile);if(!before.isFile())throw Error();file=await open(a.tokenFile,constants.O_RDONLY|(constants.O_NOFOLLOW??0));const stat=await file.stat();if(!stat.isFile()||stat.size>65536||(process.platform!=='win32'&&((stat.mode&0o077)||stat.uid!==process.getuid?.())))throw Error();token=(await file.readFile('utf8')).trim();}catch{throw new BannerbearError('Cannot read the private Bannerbear token file; use an absolute owner-only regular token-only file at most 64 KiB.',0,'CONFIG');}finally{await file?.close();}}if(!token||/[\r\n]/.test(token))throw new BannerbearError('No valid API key configured for the selected profile. Run bannerbear-cli login.',0,'CONFIG');this.tokens.set(a.name,token);return token;}
 private async pace(a:Account){const prior=this.schedules.get(a.name)??Promise.resolve();const next=prior.catch(()=>{}).then(async()=>{const delay=Math.max(0,(this.nextAt.get(a.name)??0)-Date.now());if(delay)await this.sleep(delay);this.nextAt.set(a.name,Date.now()+this.config.minIntervalMs);});this.schedules.set(a.name,next);await next;}
 async request(method:string,path:string,query:QueryParam[]=[],body?:Json|Uint8Array,hint?:string,contentType='application/json',rawResult=false):Promise<Json>{
  if(!/^\/[a-zA-Z0-9_%./-]*$/.test(path)||path.startsWith('//')||path.includes('..')||/%2e|%2f|%5c/i.test(path))throw new UsageError('Unsupported Bannerbear API path.');
  const a=selectAccount(this.config,hint),token=await this.token(a),url=new URL('/v5'+path,'https://api.bannerbear.com');for(const p of query){if(p.value===undefined)continue;if(typeof p.value==='object')throw new UsageError('Unsupported object query parameter.');url.searchParams.set(p.name,String(p.value));}
  const raw=Buffer.isBuffer(body)||body instanceof Uint8Array;const encoded=body===undefined?undefined:raw?body:JSON.stringify(body);if(encoded!==undefined&&(raw?encoded.length>5000000:Buffer.byteLength(encoded as string)>1048576))throw new UsageError('Request exceeds the local file or JSON size cap.');
  await this.pace(a);let response:Response;try{response=await this.fetcher(url,{method,redirect:'error',signal:AbortSignal.timeout(this.config.timeoutMs),headers:{Authorization:'Bearer '+token,Accept:'application/json',...(body!==undefined?{'Content-Type':contentType}:{})},...(encoded!==undefined?{body:encoded as NonNullable<Parameters<typeof fetch>[1]>['body']}:{})});}catch{throw new BannerbearError('Bannerbear request failed or timed out; its outcome may be unknown. No automatic retry or sync-to-async resubmission. Inspect existing resources before any deliberate repeat.',0,'NETWORK');}
  const chunks:Uint8Array[]=[];let bytes=0;const reader=response.body?.getReader();if(reader)try{for(;;){const part=await reader.read();if(part.done)break;bytes+=part.value.byteLength;if(bytes>5*1048576){await reader.cancel();throw new BannerbearError('Response exceeds the 5 MiB local cap; do not automatically repeat the request.',0,'API_ERROR');}chunks.push(part.value);}}finally{reader.releaseLock();}
  const text=Buffer.concat(chunks).toString('utf8');if(!response.ok){let detail='';try{detail=JSON.stringify(this.sanitize(JSON.parse(text))).slice(0,1000);}catch{}throw new BannerbearError('Bannerbear API '+response.status+(detail?': '+detail:''),response.status,response.status===429||response.status===402?'RATE_LIMIT':response.status===401||response.status===403?'AUTH':'API_ERROR');}
  if(response.status===204)return{success:true};if(!text)throw new BannerbearError('Bannerbear returned an empty response.',0,'API_ERROR');let parsed;try{parsed=JSON.parse(text);}catch{throw new BannerbearError('Bannerbear returned a non-JSON response.',0,'API_ERROR');}if(parsed===null||typeof parsed!=='object')throw new BannerbearError('Invalid Bannerbear JSON response.',0,'API_ERROR');return rawResult?parsed:this.sanitize(parsed)as Json;
 }
}
