import fs from'node:fs';import crypto from'node:crypto';import assert from'node:assert/strict';
const operations=JSON.parse(fs.readFileSync(new URL('../src/tools/operations.json',import.meta.url)));const provenance=JSON.parse(fs.readFileSync(new URL('../src/tools/api-source.json',import.meta.url)));const hash=x=>crypto.createHash('sha256').update(x).digest('hex');assert.equal(hash(fs.readFileSync(new URL('../src/tools/operations.json',import.meta.url))),provenance.openapi.distributedMetadataSha256,'Distributed metadata changed; review source and regenerate documentation before recording a new checksum.');
const args=process.argv.slice(2);if(args.length===0||args.length===1&&args[0]==='--check'){console.log(JSON.stringify({offlineMetadataCheck:true,operations:operations.length,sourceSha256:provenance.openapi.sha256}));process.exit(0);}
assert.equal(args.length,4,'Use --source /absolute/reviewed/openapi.json --sha256 SHA256');assert.equal(args[0],'--source');assert.equal(args[2],'--sha256');const raw=fs.readFileSync(args[1]);assert(raw.length<=5*1048576,'Source exceeds 5 MiB');assert.equal(hash(raw),args[3],'Reviewed source checksum mismatch');const source=JSON.parse(raw);assert.equal(source.info.version,'5.0');
function clean(v){if(Array.isArray(v))return v.map(clean);if(!v||typeof v!=='object')return v;let out={};for(const[k,x]of Object.entries(v)){if(['description','example','examples','discriminator','readOnly','writeOnly'].includes(k)||k.startsWith('x-'))continue;if(k==='$ref')out[k]=x.replace('#/components/schemas/','#/$defs/');else if(['properties','patternProperties','$defs','definitions'].includes(k))out[k]=Object.fromEntries(Object.entries(x).map(([n,s])=>[n,clean(s)]));else if(k!=='nullable')out[k]=clean(x);}if(v.nullable){if(out.type)out.type=Array.isArray(out.type)?[...out.type,'null']:[out.type,'null'];else out={anyOf:[out,{type:'null'}]};}if(out.type==='object'&&out.properties)out.additionalProperties??=false;return out;}
function refs(v){if(Array.isArray(v))return v.flatMap(refs);if(v&&typeof v==='object')return Object.entries(v).flatMap(([k,x])=>k==='$ref'?[x.split('/').at(-1)]:refs(x));return[];}
function closure(body){const need=new Set(refs(body)),done={};while(need.size){const name=need.values().next().value;need.delete(name);if(done[name])continue;assert(source.components.schemas[name],'Missing referenced schema '+name);done[name]=clean(source.components.schemas[name]);for(const ref of refs(done[name]))if(!done[ref])need.add(ref);}return done;}
const changed=[];for(const op of operations){const entry=source.paths[op.path]?.[op.method.toLowerCase()];assert(entry&&!entry.deprecated,'Selected operation missing/deprecated: '+op.name);const body=clean(entry.requestBody?.content?.['application/json']?.schema??{type:'object',additionalProperties:false});if(op.name==='generate_ai_video')body.properties.duration.type='integer';if(op.name==='create_batch')Object.assign(body.properties.items,{minItems:1,maxItems:100});const defs=closure(body);if(Object.keys(defs).length)body.$defs=defs;const params=[...(source.paths[op.path].parameters??[]),...(entry.parameters??[])].map(p=>{assert(!p.$ref,'Unresolved parameter');const s=clean(p.schema??{});if(p.in==='path')Object.assign(s,{minLength:1,maxLength:128,pattern:'^[A-Za-z0-9_-]+$'});if(p.name==='page')Object.assign(s,{minimum:1,maximum:1000000});return{name:p.name,key:p.name,in:p.in,required:p.required??false,schema:s};});try{assert.deepEqual(body,op.bodySchema);assert.deepEqual(params,op.params);}catch{changed.push(op.name);}}
assert.equal(changed.length,0,'Reviewed API input changed: '+changed.join(', ')+'. Review provider docs/fixtures, regenerate runtime metadata and all README/CMS argument tables; do not execute downloaded code.');console.log(JSON.stringify({sourceChecksumVerified:true,selectedInputsUnchanged:true,operations:operations.length,sourceBytes:raw.length}));
