import operationsData from './operations.json' with{type:'json'};
import{Ajv2020}from'ajv/dist/2020.js';import type{ValidateFunction}from'ajv';import addFormats from'ajv-formats';import{open,lstat,realpath}from'node:fs/promises';import{constants}from'node:fs';import{isAbsolute,dirname,resolve}from'node:path';import{createHash}from'node:crypto';
import type{Json,BannerbearClient,QueryParam}from'../api/client.js';import{UsageError,BannerbearError}from'../api/errors.js';import type{Config}from'../config.js';import type{Risk}from'@thenavidm/slipway';
export type Operation={name:string;title:string;description:string;operationId:string;method:string;path:string;group:string;risk:Risk;params:{name:string;key:string;in:string;required:boolean;schema:Json}[];bodySchema:Json;bodyRequired:boolean;paginated:boolean;rawAsset:boolean;contentTypes:string[];secretDelivery:boolean};
export type ToolSpec={name:string;title:string;description:string;group:string;inputSchema:Json;risk:Risk;handler:(args:Json,client:BannerbearClient)=>Promise<unknown>};
export const OPERATIONS=operationsData as unknown as Operation[];const ajv=new Ajv2020({allErrors:true,strict:false});(addFormats as unknown as(a:typeof ajv)=>void)(ajv);const compiled=new Map<object,ValidateFunction>();
// Each schema compiles on first use: compiling all of them at load held back the server's first answer. compileAll() runs them in tests.
function validatorFor(schema:object){let v=compiled.get(schema);if(!v){v=ajv.compile(schema);compiled.set(schema,v);}return v;}
function check(v:ValidateFunction,x:unknown){if(!v(x))throw new UsageError(ajv.errorsText(v.errors,{separator:'; '}));}
const obj=(properties:Json,required:string[]=[])=>({type:'object',properties,required,additionalProperties:false});
function fieldsFor(o:Operation):Json{const properties:Json=Object.fromEntries(o.params.map(p=>[p.key,p.schema]));properties.account={type:'string',description:'Exact private workspace profile label; no fallback to another profile key.'};if(o.risk!=='read')properties.confirm={type:'boolean',description:'Must be true for this exact requested render, upload, edit, install or delete.'};if(o.bodyRequired){properties.payload={...o.bodySchema,description:'Complete current native JSON body. Use payload or payload_file exclusively.'};properties.payload_file={type:'string',minLength:1,description:'Regular non-symlink local JSON file, at most 1 MiB.'};}if(o.rawAsset){properties.asset_file={type:'string',minLength:1,description:'Regular non-symlink local file, at most 5,000,000 bytes. Uploaded only after confirmation.'};properties.content_type={type:'string',enum:o.contentTypes,description:'Exact documented Content-Type for these raw file bytes.'};}if(o.secretDelivery)properties.secret_result_file={type:'string',minLength:1,description:'New absolute JSON file in an existing private directory; exclusive 0600 creation before the API request. No overwrite; signing key never appears in output.'};return{...obj(properties,[...o.params.filter(p=>p.required).map(p=>p.key),...(o.rawAsset?['asset_file','content_type']:[]),...(o.secretDelivery?['secret_result_file']:[])]),...(o.bodySchema.$defs?{$defs:o.bodySchema.$defs}:{})};}
function native(name:string){const o=OPERATIONS.find(x=>x.name===name);if(!o)throw new UsageError('Unknown named operation.');return o;}
async function localBytes(path:string,cap:number){let f;try{if(!(await lstat(path)).isFile())throw Error();f=await open(path,constants.O_RDONLY|(constants.O_NOFOLLOW??0));const s=await f.stat();if(!s.isFile()||s.size>cap)throw Error();const b=await f.readFile();if(b.length>cap)throw Error();return b;}catch{throw new UsageError('Input file must be a regular non-symlink local file within the documented size cap.');}finally{await f?.close();}}
export async function prepare(o:Operation,a:Json,c:BannerbearClient){
 if(a.payload!==undefined&&a.payload_file!==undefined)throw new UsageError('Use payload or payload_file, not both.');let body:Json|Uint8Array|undefined;
 if(o.bodyRequired){if(a.payload===undefined&&!a.payload_file)throw new UsageError('Provide payload or payload_file.');try{body=a.payload_file?JSON.parse((await localBytes(a.payload_file,1048576)).toString('utf8')):a.payload;}catch(e){if(e instanceof UsageError)throw e;throw new UsageError('Invalid payload_file JSON.');}check(validatorFor(o.bodySchema),body);}
 if(o.rawAsset){body=await localBytes(a.asset_file,5000000);if(!body.length)throw new UsageError('Empty asset files are refused.');}
 const path=o.params.filter(p=>p.in==='path').reduce((s,p)=>s.replace('{'+p.name+'}',encodeURIComponent(String(a[p.key]))),o.path),query:QueryParam[]=o.params.filter(p=>p.in==='query'&&a[p.key]!==undefined).map(p=>({name:p.name,value:a[p.key]}));return{path,query,body,account:a.account??c.config.defaultAccount??'default',contentType:o.rawAsset?a.content_type:'application/json'};
}
async function reserveSecret(path:string){try{if(!isAbsolute(path))throw Error();const parent=dirname(path),s=await lstat(parent);if(!s.isDirectory()||(process.platform!=='win32'&&((s.mode&0o077)||s.uid!==process.getuid?.())))throw Error();const actual=await realpath(parent);if(process.platform==='win32'?actual.toLowerCase()!==resolve(parent).toLowerCase():actual!==resolve(parent))throw Error();return await open(path,'wx',0o600);}catch{throw new UsageError('secret_result_file must be a new absolute file in a canonical existing owner-only directory; no overwrite or symlink. Windows ACLs must be restricted by the owner.');}}
async function execute(o:Operation,a:Json,c:BannerbearClient){
 const p=await prepare(o,a,c);const output=o.secretDelivery?await reserveSecret(a.secret_result_file):undefined;
 try{
  let result:unknown;
  try{result=await c.request(o.method,p.path,p.query,p.body,a.account,p.contentType,!!output);}
  catch(e){if(output){try{await output.writeFile(JSON.stringify({operation:o.name,providerOutcome:'not verified',notice:'Reserved before request; failure may have an unknown outcome. Inspect the provider before repeating. No key captured.'})+'\n');await output.sync();}catch{/* Preserve the original provider failure; never expose a raw result. */}}throw e;}
  if(output){
   try{await output.writeFile(JSON.stringify({operation:o.name,result})+'\n');await output.sync();}
   catch{throw new BannerbearError('Provider returned a result but private file persistence failed. Inspect the reserved private file and provider state before repeating. No signing key was returned to model context.');}
   return{result:c.sanitize(result),secretResultSaved:true,secret_result_file:a.secret_result_file,notice:'Private result saved. Keep signing keys out of model context and repositories; no automatic repeat.'};
  }return result;
 }finally{await output?.close();}
}
export const ALL_TOOLS:ToolSpec[]=OPERATIONS.map(o=>({name:o.name,title:o.title,description:o.description+(o.risk==='read'?' Read operation.':' Mandatory confirmation before provider execution; one submission only.'),group:o.group,inputSchema:fieldsFor(o),risk:o.risk,handler:(a,c)=>execute(o,a,c)}));
ALL_TOOLS.push({name:'list_accounts',title:'List private profiles',description:'Local profile labels, default and auth method only; no keys, paths or provider identity. No network.',group:'Local',risk:'read',inputSchema:obj({}),handler:async(_,c)=>({accounts:c.config.accounts.map(a=>({name:a.name,default:a.name===c.config.defaultAccount,auth:a.tokenFile?'token_file':a.apiToken?'api_key':'not_configured'}))})});
ALL_TOOLS.push({name:'get_operation_schema',title:'Inspect native schema',description:'Return the complete current path/query/body schema for a selected operation. Local only.',group:'Local',risk:'read',inputSchema:obj({operation:{type:'string',enum:OPERATIONS.map(o=>o.name)}},['operation']),handler:async a=>{const o=native(a.operation);return{operation:o.name,method:o.method,path:o.path,parameters:o.params,body:o.bodySchema,contentTypes:o.contentTypes,requiresPrivateResultFile:o.secretDelivery};}});
ALL_TOOLS.push({name:'get_layer_schema',title:'Inspect a layer schema',description:'Return a complete selected native layer or animation keyframe schema from the pinned V5 definitions. No network.',group:'Local',risk:'read',inputSchema:obj({layer:{type:'string',enum:Object.keys(native('create_image_template').bodySchema.$defs).filter(k=>k.startsWith('Layer')).concat(['Keyframes'])}},['layer']),handler:async a=>{const defs={...native('create_image_template').bodySchema.$defs,...native('create_animation_template').bodySchema.$defs};return{schema:defs[a.layer],$defs:defs};}});
ALL_TOOLS.push({name:'preview_operation',title:'Preview a request',description:'Validate and preview an exact local named request. No authentication, provider validation or quota estimate. Raw asset previews reveal only byte count/hash.',group:'Local',risk:'read',inputSchema:obj({operation:{type:'string',enum:OPERATIONS.map(o=>o.name)},arguments:{type:'object'}},['operation','arguments']),handler:async(a,c)=>{const o=native(a.operation);validateArguments(ALL_TOOLS.find(t=>t.name===o.name)!,a.arguments);const p=await prepare(o,a.arguments,c);return{operation:o.name,method:o.method,...p,body:(Buffer.isBuffer(p.body)||p.body instanceof Uint8Array)?{bytes:p.body.length,sha256:createHash('sha256').update(p.body).digest('hex')}:p.body,localOnly:true,providerValidated:false};}});
ALL_TOOLS.push({name:'query_pages',title:'Bounded native pages',description:'Read 1–5 pages of a selected native paginated read. Stop at an empty page; report a resume page at the cap. No completeness assumption from a short page.',group:'Reads',risk:'read',inputSchema:obj({operation:{type:'string',enum:OPERATIONS.filter(o=>o.risk==='read'&&o.paginated).map(o=>o.name)},arguments:{type:'object'},max_pages:{type:'integer',minimum:1,maximum:5,default:1}},['operation','arguments']),handler:async(a,c)=>{const o=native(a.operation);if(!o.paginated||o.risk!=='read')throw new UsageError('Unsupported pagination operation.');validateArguments(ALL_TOOLS.find(t=>t.name===o.name)!,a.arguments);let page=a.arguments.page??1;const pages=[];let exhausted=false;for(let i=0;i<(a.max_pages??1);i++){const result=await execute(o,{...a.arguments,page},c);if(!Array.isArray(result))throw new UsageError('Unexpected native list shape; pagination stopped.');pages.push(result);if(!result.length){exhausted=true;break;}page++;}return{pages,pagesRead:pages.length,emptyPageReached:exhausted,continuationUnknown:!exhausted,resumePage:exhausted?undefined:page};}});
const resources=['images','animations','batches','tool_jobs','workflow_runs'];
ALL_TOOLS.push({name:'poll_job',title:'Bounded existing job polling',description:'Read only an existing image, animation, batch, tool job or workflow run. At most 20 GETs, no create/resubmit. Completed/failed terminal states stop; missing/unrecognised state stops as unknown.',group:'Reads',risk:'read',inputSchema:obj({resource:{type:'string',enum:resources},uid:{type:'string',pattern:'^[A-Za-z0-9_-]+$',minLength:1,maxLength:128},account:{type:'string'},max_polls:{type:'integer',minimum:1,maximum:20,default:3},interval_ms:{type:'integer',minimum:100,maximum:5000,default:1000}},['resource','uid']),handler:async(a,c)=>{let result:Json={};let reads=0;const n=a.max_polls??3;for(let i=0;i<n;i++){result=await c.request('GET','/'+a.resource+'/'+a.uid,[],undefined,a.account);reads++;if(['completed','failed'].includes(result.status))return{reads,terminal:true,result};if(!['pending','queued','running'].includes(result.status))return{reads,terminal:false,continuationUnknown:true,result};if(i+1<n)await new Promise(r=>setTimeout(r,a.interval_ms??1000));}return{reads,terminal:false,limitReached:true,result};}});
const batch=native('create_batch');const batchFields:Json={payload:batch.bodySchema,payload_file:{type:'string',minLength:1},account:{type:'string'}};
function canonical(v:unknown):string{if(Array.isArray(v))return'['+v.map(canonical).join(',')+']';if(v&&typeof v==='object')return'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical((v as Json)[k])).join(',')+'}';return JSON.stringify(v);}
async function batchPlan(a:Json,c:BannerbearClient){const {preview_sha256,confirm,...args}=a;validateArguments(ALL_TOOLS.find(t=>t.name===batch.name)!,args);const p=await prepare(batch,args,c);const body=p.body as Json;const plan={method:batch.method,path:p.path,profile:(a.account??c.config.defaultAccount)||'default',body};return{...plan,items:body.items.length,preview_sha256:createHash('sha256').update(canonical(plan)).digest('hex'),localOnly:true,providerValidated:false,creditCostCalculated:false};}
ALL_TOOLS.push({name:'preview_render_batch',title:'Review a render batch',description:'Local schema-validated 1–100 native image payload review. Digest binds exact order, method/path, profile label and body. No provider state or price validation.',group:'Render review',risk:'read',inputSchema:{...obj(batchFields),$defs:batch.bodySchema.$defs},handler:batchPlan});
ALL_TOOLS.push({name:'apply_render_batch',title:'Submit the reviewed batch',description:'Validate the same reviewed digest plus explicit confirmation, then submit one native batch. Direct create_batch also needs confirmation but does not require a digest. No retry.',group:'Render review',risk:'destructive',inputSchema:{...obj({...batchFields,preview_sha256:{type:'string',pattern:'^[0-9a-f]{64}$'},confirm:{type:'boolean'}},['preview_sha256']),$defs:batch.bodySchema.$defs},handler:async(a,c)=>{const p=await batchPlan(a,c);if(a.preview_sha256!==p.preview_sha256)throw new UsageError('Reviewed render batch changed; preview the exact profile and payload again.');return c.request('POST',p.path,[],p.body,a.account);}});
export function validateArguments(t:ToolSpec,a:Json){check(validatorFor(t.inputSchema),a);}
/** Compile every input and body schema, as loading once did, so a test can prove they all compile. */
export function compileAll(){for(const t of ALL_TOOLS)validatorFor(t.inputSchema);for(const o of OPERATIONS)validatorFor(o.bodySchema);return compiled.size;}
export function visibleTools(c:Config){return ALL_TOOLS.filter(t=>!c.readOnly||t.risk==='read');}
